version: '2'

services:
  php:
    build: php
    ports:
      - "80:80"
      - "443:443"
      - "9001:9001"
    volumes:
      - ./php/www:/var/www/html
    environment:
      XDEBUG_CONFIG: "remote_host=172.19.0.1"
    links:
      - db

  db:
    image: mysql:5.7
    volumes: 
     - /var/lib/mysql
    environment: 
     - MYSQL_ROOT_PASSWORD=hunter2
     - MYSQL_DATABASE=database
