version: '2.1'
services:
    php:
        build: php
        dns:
            - 192.168.1.10
            - 8.8.8.8
            - 8.8.4.4
        ports:
            - "80:80"
        volumes:
            - ~/sources:/var/www/html
    redis:
        image: redis:latest
