name: PR commits
on: pull_request
jobs:
  build:
    name: Trigger Benchmarks

    runs-on: ubuntu-latest

    steps:
      - name: Handle Incoming Pull-Request
        env:
          DISPATCH_REPO: "benchmarks"
          DISPATCH_OWNER: "npm"
          EVENT_NAME: ${{ github.event_name }}
          EVENT_ACTION: ${{ github.event.action }}
          REPO: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
          PR_COMMITS_URL: ${{ github.event.pull_request.commits_url }}
          PR_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          AUTH_TOKEN: ${{ secrets.NPM_DEPLOY_USER_PAT }}
        run: |
          # Dispatch Handler
          dispatch_request () {
            echo "Dispatching request..."
            REF_SHA=$1
            echo "${REF_SHA}"
            echo "All branch"
            git branch --contains "${REF_SHA}"
            echo "QA branch"
            git branch --contains "${REF_SHA}" | grep qa
          }


          # Fetch the head commit sha, since it doesn't exist in the body of this event
          COMMIT_SHA=$(curl -s "${PR_COMMITS_URL}" | jq -r '.[0].sha')
          # Dispatch request for benchmarks
          dispatch_request "${COMMIT_SHA}"
